//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.26 at 03:23:27 PM BST 
//
package com.vehicle.org.proxama;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlRootElement;

 /**
  * JaxB XmlElements
  * @author NK
  *
  */
@XmlRootElement(name="proxama-data-list")
    public  class ProxamaDataList {

        protected List<ProxamaAPIPOJO> proxamaData;

		public List<ProxamaAPIPOJO> getProxamaData() {
			 if (proxamaData == null) {
				 proxamaData = new ArrayList<ProxamaAPIPOJO>();
	            }
			 
			return this.proxamaData;
		}

		public void setProxamaData(List<ProxamaAPIPOJO> proxamaData) {
			this.proxamaData = proxamaData;
		}
}
