//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 07:15:08 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.crossing.com/BridgeCrossingWS/")
package com.crossing.www.BridgeCrossingWS;
